# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("task.proto", :syntax => :proto3) do
    add_message "Task" do
      optional :id, :int32, 1
      optional :title, :string, 2
    end
  end
end

Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Task").msgclass
