# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/task.proto
# command: protoc --ruby_out=./backend/lib proto/task.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/task.proto", :syntax => :proto3) do
    add_message "Task" do
      optional :id, :int32, 1
      optional :title, :string, 2
    end
  end
end

module Protos
  Task = Google::Protobuf::DescriptorPool.generated_pool.lookup("Task").msgclass
end
